name: Deploy to Netlify
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      - name: Deploy to Netlify
        run: netlify deploy --prod --dir=.
        env:
          NETLIFY_AUTH_TOKEN: nfp_6vkXtfuCyUEYm4uCpWeRJr24vm973opp12d8
          NETLIFY_SITE_ID: f73e75bb-1b95-4584-9f3a-208054ac5c75